In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
data=pd.read_csv("C:\\Users\\raghu\\Downloads\\dropout.csv")

In [4]:
data

Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
0     0.0200   0.0371   0.0428   0.0207   0.0954   0.0986   0.1539   0.1601   
1     0.0453   0.0523   0.0843   0.0689   0.1183   0.2583   0.2156   0.3481   
2     0.0262   0.0582   0.1099   0.1083   0.0974   0.2280   0.2431   0.3771   
3     0.0100   0.0171   0.0623   0.0205   0.0205   0.0368   0.1098   0.1276   
4     0.0762   0.0666   0.0481   0.0394   0.0590   0.0649   0.1209   0.2467   
..       ...      ...      ...      ...      ...      ...      ...      ...   
203   0.0187   0.0346   0.0168   0.0177   0.0393   0.1630   0.2028   0.1694   
204   0.0323   0.0101   0.0298   0.0564   0.0760   0.0958   0.0990   0.1018   
205   0.0522   0.0437   0.0180   0.0292   0.0351   0.1171   0.1257   0.1178   
206   0.0303   0.0353   0.0490   0.0608   0.0167   0.1354   0.1465   0.1123   
207   0.0260   0.0363   0.0136   0.0272   0.0214   0.0338   0.0655   0.1400   

     Column9  Column10  ...  Column52  Column53  Column54  Column55  Column56  \
0     0.3109    0.2111  ...    0.0027    0.0065    0.0159    0.0072    0.0167   
1     0.3337    0.2872  ...    0.0084    0.0089    0.0048    0.0094    0.0191   
2     0.5598    0.6194  ...    0.0232    0.0166    0.0095    0.0180    0.0244   
3     0.0598    0.1264  ...    0.0121    0.0036    0.0150    0.0085    0.0073   
4     0.3564    0.4459  ...    0.0031    0.0054    0.0105    0.0110    0.0015   
..       ...       ...  ...       ...       ...       ...       ...       ...   
203   0.2328    0.2684  ...    0.0116    0.0098    0.0199    0.0033    0.0101   
204   0.1030    0.2154  ...    0.0061    0.0093    0.0135    0.0063    0.0063   
205   0.1258    0.2529  ...    0.0160    0.0029    0.0051    0.0062    0.0089   
206   0.1945    0.2354  ...    0.0086    0.0046    0.0126    0.0036    0.0035   
207   0.1843    0.2354  ...    0.0146    0.0129    0.0047    0.0039    0.0061   

     Column57  Column58  Column59  Column60  Column61  
0      0.0180    0.0084    0.0090    0.0032         R  
1      0.0140    0.0049    0.0052    0.0044         R  
2      0.0316    0.0164    0.0095    0.0078         R  
3      0.0050    0.0044    0.0040    0.0117         R  
4      0.0072    0.0048    0.0107    0.0094         R  
..        ...       ...       ...       ...       ...  
203    0.0065    0.0115    0.0193    0.0157         M  
204    0.0034    0.0032    0.0062    0.0067         M  
205    0.0140    0.0138    0.0077    0.0031         M  
206    0.0034    0.0079    0.0036    0.0048         M  
207    0.0040    0.0036    0.0061    0.0115         M  

[208 rows x 61 columns]

In [5]:
data.sample(5)

Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
196   0.0050   0.0017   0.0270   0.0450   0.0958   0.0830   0.0879   0.1220   
149   0.0207   0.0535   0.0334   0.0818   0.0740   0.0324   0.0918   0.1070   
110   0.0210   0.0121   0.0203   0.1036   0.1675   0.0418   0.0723   0.0828   
78    0.0231   0.0351   0.0030   0.0304   0.0339   0.0860   0.1738   0.1351   
43    0.0093   0.0269   0.0217   0.0339   0.0305   0.1172   0.1450   0.0638   

     Column9  Column10  ...  Column52  Column53  Column54  Column55  Column56  \
196   0.1977    0.2282  ...    0.0165    0.0056    0.0010    0.0027    0.0062   
149   0.1553    0.1234  ...    0.0033    0.0050    0.0190    0.0103    0.0121   
110   0.0494    0.0686  ...    0.0117    0.0101    0.0061    0.0031    0.0099   
78    0.1063    0.0347  ...    0.0106    0.0097    0.0022    0.0052    0.0072   
43    0.0740    0.1360  ...    0.0212    0.0091    0.0056    0.0086    0.0092   

     Column57  Column58  Column59  Column60  Column61  
196    0.0024    0.0063    0.0017    0.0028         M  
149    0.0042    0.0090    0.0070    0.0099         M  
110    0.0080    0.0107    0.0161    0.0133         M  
78     0.0056    0.0038    0.0043    0.0030         R  
43     0.0070    0.0116    0.0060    0.0110         R  

[5 rows x 61 columns]

In [6]:
data.shape

(208, 61)

In [7]:
data.isnull()


Column1  Column2  Column3  Column4  Column5  Column6  Column7  Column8  \
0      False    False    False    False    False    False    False    False   
1      False    False    False    False    False    False    False    False   
2      False    False    False    False    False    False    False    False   
3      False    False    False    False    False    False    False    False   
4      False    False    False    False    False    False    False    False   
..       ...      ...      ...      ...      ...      ...      ...      ...   
203    False    False    False    False    False    False    False    False   
204    False    False    False    False    False    False    False    False   
205    False    False    False    False    False    False    False    False   
206    False    False    False    False    False    False    False    False   
207    False    False    False    False    False    False    False    False   

     Column9  Column10  ...  Column52  Column53  Column54  Column55  Column56  \
0      False     False  ...     False     False     False     False     False   
1      False     False  ...     False     False     False     False     False   
2      False     False  ...     False     False     False     False     False   
3      False     False  ...     False     False     False     False     False   
4      False     False  ...     False     False     False     False     False   
..       ...       ...  ...       ...       ...       ...       ...       ...   
203    False     False  ...     False     False     False     False     False   
204    False     False  ...     False     False     False     False     False   
205    False     False  ...     False     False     False     False     False   
206    False     False  ...     False     False     False     False     False   
207    False     False  ...     False     False     False     False     False   

     Column57  Column58  Column59  Column60  Column61  
0       False     False     False     False     False  
1       False     False     False     False     False  
2       False     False     False     False     False  
3       False     False     False     False     False  
4       False     False     False     False     False  
..        ...       ...       ...       ...       ...  
203     False     False     False     False     False  
204     False     False     False     False     False  
205     False     False     False     False     False  
206     False     False     False     False     False  
207     False     False     False     False     False  

[208 rows x 61 columns]

In [9]:
data.isna().sum()

Column1     0
Column2     0
Column3     0
Column4     0
Column5     0
           ..
Column57    0
Column58    0
Column59    0
Column60    0
Column61    0
Length: 61, dtype: int64

In [10]:
data.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8', 'Column9', 'Column10', 'Column11', 'Column12',
       'Column13', 'Column14', 'Column15', 'Column16', 'Column17', 'Column18',
       'Column19', 'Column20', 'Column21', 'Column22', 'Column23', 'Column24',
       'Column25', 'Column26', 'Column27', 'Column28', 'Column29', 'Column30',
       'Column31', 'Column32', 'Column33', 'Column34', 'Column35', 'Column36',
       'Column37', 'Column38', 'Column39', 'Column40', 'Column41', 'Column42',
       'Column43', 'Column44', 'Column45', 'Column46', 'Column47', 'Column48',
       'Column49', 'Column50', 'Column51', 'Column52', 'Column53', 'Column54',
       'Column55', 'Column56', 'Column57', 'Column58', 'Column59', 'Column60',
       'Column61'],
      dtype='object')

In [12]:
data["Column61"].value_counts()

M    111
R     97
Name: Column61, dtype: int64

In [19]:
x=data.drop("Column61",axis="columns")
y=data["Column61"]

In [20]:
y

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: Column61, Length: 208, dtype: object

In [21]:
y=pd.get_dummies(y,drop_first=True)

In [22]:
y

R
0    1
1    1
2    1
3    1
4    1
..  ..
203  0
204  0
205  0
206  0
207  0

[208 rows x 1 columns]

In [23]:
y.value_counts()

R
0    111
1     97
dtype: int64

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
x_train.shape

(166, 60)

In [42]:
model=keras.Sequential([
    keras.layers.Dense(30,input_dim=60,activation="relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(15,activation="relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1,activation="sigmoid")                   
                      
])

In [43]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [44]:
model.fit(x_train,y_train,epochs=100)

Epoch 1/100
6/6 [==============================] - 2s 4ms/step - loss: 0.7429 - accuracy: 0.4880
Epoch 2/100
6/6 [==============================] - 0s 4ms/step - loss: 0.7292 - accuracy: 0.5422
Epoch 3/100
6/6 [==============================] - 0s 3ms/step - loss: 0.7242 - accuracy: 0.4880
Epoch 4/100
6/6 [==============================] - 0s 3ms/step - loss: 0.7105 - accuracy: 0.5783
Epoch 5/100
6/6 [==============================] - 0s 3ms/step - loss: 0.7204 - accuracy: 0.5301
Epoch 6/100
6/6 [==============================] - 0s 5ms/step - loss: 0.7197 - accuracy: 0.4940
Epoch 7/100
6/6 [==============================] - 0s 3ms/step - loss: 0.7296 - accuracy: 0.4277
Epoch 8/100
6/6 [==============================] - 0s 3ms/step - loss: 0.7300 - accuracy: 0.4578
Epoch 9/100
6/6 [==============================] - 0s 4ms/step - loss: 0.7156 - accuracy: 0.5060
Epoch 10/100
6/6 [==============================] - 0s 3ms/step - loss: 0.7158 - accuracy: 0.5060
Epoch 11/100
6/6 [===========

6/6 [==============================] - 0s 4ms/step - loss: 0.5621 - accuracy: 0.7470
Epoch 85/100
6/6 [==============================] - 0s 3ms/step - loss: 0.5523 - accuracy: 0.7530
Epoch 86/100
6/6 [==============================] - 0s 5ms/step - loss: 0.5610 - accuracy: 0.6988
Epoch 87/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5197 - accuracy: 0.7651
Epoch 88/100
6/6 [==============================] - 0s 2ms/step - loss: 0.5623 - accuracy: 0.7470
Epoch 89/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5501 - accuracy: 0.7470
Epoch 90/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5407 - accuracy: 0.7470
Epoch 91/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5551 - accuracy: 0.7108
Epoch 92/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5120 - accuracy: 0.7952
Epoch 93/100
6/6 [==============================] - 0s 4ms/step - loss: 0.5504 - accuracy: 0.7169
Epoch 94/100
6/6 [===============

In [45]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 4ms/step - loss: 0.5452 - accuracy: 0.7619


[0.5451834797859192, 0.761904776096344]

In [33]:
y_test

R
15   1
172  0
201  0
108  0
120  0
141  0
149  0
17   1
169  0
7    1
11   1
35   1
132  0
80   1
88   1
105  0
185  0
137  0
158  0
21   1
200  0
191  0
202  0
140  0
144  0
101  0
156  0
92   1
131  0
28   1
154  0
167  0
102  0
111  0
41   1
16   1
97   0
114  0
130  0
30   1
59   1
106  0

In [46]:
y_pred=model.predict(x_test)

2/2 [==============================] - 0s 10ms/step


In [35]:
y_pred

array([[0.93135726],
       [0.28356826],
       [0.02527315],
       [0.68317723],
       [0.49908456],
       [0.02629642],
       [0.06760988],
       [0.92719764],
       [0.62900877],
       [0.04707124],
       [0.8931546 ],
       [0.30673057],
       [0.13818844],
       [0.71411246],
       [0.92045635],
       [0.56901443],
       [0.00462586],
       [0.01839376],
       [0.5064042 ],
       [0.96401   ],
       [0.0201586 ],
       [0.24757484],
       [0.11048817],
       [0.0128865 ],
       [0.07388925],
       [0.62505114],
       [0.14548148],
       [0.71728706],
       [0.07769692],
       [0.23874766],
       [0.4160244 ],
       [0.56028247],
       [0.6205    ],
       [0.24775709],
       [0.99583745],
       [0.63059485],
       [0.87466407],
       [0.29870254],
       [0.5367573 ],
       [0.7819531 ],
       [0.9917989 ],
       [0.79072374]], dtype=float32)

In [47]:
y_pred=y_pred.reshape(-1)

In [48]:
y_pred

array([0.7875977 , 0.4311298 , 0.2650186 , 0.60035306, 0.52825356,
       0.22904816, 0.331763  , 0.69131196, 0.6741439 , 0.32857895,
       0.6693692 , 0.5466445 , 0.33261192, 0.52300507, 0.67904973,
       0.47960272, 0.19352345, 0.21445814, 0.68044823, 0.70460665,
       0.28177208, 0.3853453 , 0.31733418, 0.18608245, 0.25842017,
       0.39763838, 0.50567657, 0.50501585, 0.3237643 , 0.4336066 ,
       0.42132956, 0.60708493, 0.42252928, 0.3993755 , 0.86911243,
       0.6253194 , 0.7290412 , 0.4190777 , 0.34510553, 0.6584092 ,
       0.85601264, 0.62656224], dtype=float32)

In [49]:
y_pred=np.round(y_pred)

In [50]:
y_pred

array([1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 0., 1., 1., 1.], dtype=float32)

In [51]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

         0.0       0.71      0.91      0.80        22
         1.0       0.86      0.60      0.71        20

    accuracy                           0.76        42
   macro avg       0.79      0.75      0.75        42
weighted avg       0.78      0.76      0.76        42

