In [21]:
import tensorflow as tf
from tensorflow.keras import layers,models,losses

In [2]:
import numpy as np

In [13]:
x=np.array([1,2,3,4,5,6,7,8,9,10])
y=np.array([4,8,12,16,20,24,28,32,36,40])

In [14]:
model=models.Sequential([
    layers.Dense(1,input_shape=(1,))
])

In [27]:
model.compile(optimizer='sgd',
             loss=losses.mean_absolute_error,
             metrics=['accuracy'])

In [29]:
model.fit(x,y,epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 18ms/step - loss: 25.4937 - accuracy: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 16ms/step - loss: 25.1812 - accuracy: 0.0000e+00
Epoch 3/50
1/1 [==============================] - 0s 13ms/step - loss: 24.8687 - accuracy: 0.0000e+00
Epoch 4/50
1/1 [==============================] - 0s 13ms/step - loss: 24.5562 - accuracy: 0.0000e+00
Epoch 5/50
1/1 [==============================] - 0s 13ms/step - loss: 24.2437 - accuracy: 0.0000e+00
Epoch 6/50
1/1 [==============================] - 0s 13ms/step - loss: 23.9312 - accuracy: 0.0000e+00
Epoch 7/50
1/1 [==============================] - 0s 14ms/step - loss: 23.6187 - accuracy: 0.0000e+00
Epoch 8/50
1/1 [==============================] - 0s 14ms/step - loss: 23.3062 - accuracy: 0.0000e+00
Epoch 9/50
1/1 [==============================] - 0s 13ms/step - loss: 22.9937 - accuracy: 0.0000e+00
Epoch 10/50
1/1 [==============================] - 0s 4ms/step - loss: 22.6812 - a

In [30]:
model.predict([11])

1/1 [==============================] - 0s 149ms/step


array([[23.6126]], dtype=float32)

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [32]:
pip install torch

     ------------------------------------ 192.2/192.2 MB 570.7 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [8]:
class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.fc1=nn.Linear(1,10)
        self.fc2=nn.Linear(10,1)
    def forward(self,x):
        x=torch.relu(self.fc1(x))
        x=self.fc2(x)
        return x
net=Net()


In [9]:
criterion=nn.MSELoss()
optimizer=optim.SGD(net.parameters(),lr=0.01)
x=torch.randn(20,1)
y=x*2

In [10]:
for epoch in range(100):
    optimizer.zero_grad()
    outputs=net(x)
    loss=criterion(outputs,y)
    loss.backward()
    optimizer.step()

In [11]:
print('Finished Training')
print(x)
print(y)

Finished Training
tensor([[-0.1244],
        [-1.5127],
        [-1.7888],
        [ 0.0353],
        [-0.2576],
        [-0.1378],
        [ 1.7822],
        [ 1.0329],
        [ 0.3886],
        [-0.3868],
        [ 3.6726],
        [ 0.8855],
        [ 0.9863],
        [ 0.0448],
        [-1.3333],
        [-0.9765],
        [ 1.9148],
        [-0.8168],
        [-0.9432],
        [ 0.4331]])
tensor([[-0.2488],
        [-3.0254],
        [-3.5775],
        [ 0.0706],
        [-0.5152],
        [-0.2756],
        [ 3.5644],
        [ 2.0657],
        [ 0.7772],
        [-0.7735],
        [ 7.3452],
        [ 1.7711],
        [ 1.9727],
        [ 0.0896],
        [-2.6666],
        [-1.9529],
        [ 3.8295],
        [-1.6337],
        [-1.8864],
        [ 0.8662]])


In [12]:
x_test=torch.randn(1,1)
print(x_test)
prediction=net(x_test)
prediction

tensor([[-1.2936]])


tensor([[-2.5088]], grad_fn=<AddmmBackward0>)